i2s_audio:
  - id: i2s_bus
    i2s_lrclk_pin: GPIO41
    i2s_bclk_pin: GPIO38

microphone:
  - platform: i2s_audio
    id: mic
    i2s_audio_id: i2s_bus
    i2s_din_pin: GPIO42
    adc_type: external
    pdm: true
    sample_rate: 16000
    bits_per_sample: 16bit
    channel: right

speaker:
  - platform: i2s_audio
    id: spk
    i2s_audio_id: i2s_bus
    i2s_dout_pin: GPIO17
    dac_type: external
    sample_rate: 16000
    bits_per_sample: 16bit

media_player:
  - platform: speaker
    name: "${friendly_name}"
    id: mp
    announcement_pipeline:
      speaker: spk

voice_assistant:
  id: va
  microphone: mic
  media_player: mp
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 4.0

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Voice Button"
    on_press:
      - voice_assistant.start
