name: Build ESPHome
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ESPHome
        run: |
          pip install esphome

      - name: Build ESPHome
        run: |
          esphome compile xh-s3e-ai.yaml
          ls -la
          ls -la .esphome/ || true
          ls -la .esphome/build/ || true

      - name: Upload entire workspace
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .
          retention-days: 1